version: '3.8'

services:
  portfolio-dev:
    image: node:18-alpine
    container_name: portfolio-dev
    working_dir: /app

    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - "3001:3000"

    command: >
      sh -c "npm install && npm start"

    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=0.0.0.0
      - REACT_APP_ENV=development

    labels:
      - "coolify.healthcheck=false"

    tty: true
    stdin_open: true
